### ISSUE TITLE
Create Polling for New Team Meeting Schedule

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-operations#11]
**Tasks:**

- [x] Create Google Sheet for polling of new team meeting schedule
https://docs.google.com/forms/d/e/1FAIpQLSdbOXsFx-FozdCYAslabOOMlcDRs67XCm90CfnonIsTFeWRfg/viewform
- [X] Inform all of team members to fill the Google Sheet
@zicozibu @andreassosilo @danivideda @jordyvincent @YanTirta @CryptoCaliburn @andrecahyadi @dionsetyotomo @shokhibulburhan @syarbel 
- [x] Gather all of the data @danivideda 
- [x] Inform the team member, when is the best time to do team meeting, where all of the members mostly could attend

**Comment by andrecahyadi** [comment]
Updated tasks

**Comment by andreassosilo** [comment]
Closed. Cannot find better day based on the input. We will still doing the core team meeting every Friday.
