### ISSUE TITLE
Update Cardano Indonesia GitHub Description

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-operations#13]
**Tasks:**

- [x] Update the description for our Cardano Indonesia GitHub
- [x] Please add more description on what we are and what we do under Cardano Indonesia
- [x] Add description on Eastern Town Hall Indonesia, such as: schedule or what is the purpose of Eastern Town Hall itself
- [ ] @YanTirta @andrecahyadi @zicozibu : please edit it accordingly

**Comment by zicozibu** [comment]
How about this:

🇮🇩  Kami adalah sekelompok orang dengan berbagai macam latar belakang dengan ketertarikan yang sama di Cardano.
Kami bergerak untuk:
- mengenalkan,
- mengedukasi,
- mendiskusikan dan,
- melakukan berbagai macam proyek di Cardano,
khususnya untuk orang-orang Indonesia dan untuk negara Indonesia.

🇺🇸  We are a group of people with varying backgrounds with a unified interest in Cardano. 
We set to:
- introduce, 
- educate, 
- discuss and,
- do projects in Cardano, 
specifically to Indonesians and for Indonesia.

**Comment by andreassosilo** [comment]
Okay, nice bro @zicozibu . Keren banget. Gimana, ada masukkan kah bro @YanTirta atau bro @andrecahyadi ?

**Comment by andrecahyadi** [comment]
@zicozibu Mantap Pak Andy, dari saya ok

**Comment by YanTirta** [comment]
Same here udah keren! Thanks Mas Andy!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by andrecahyadi** [comment]
Tambahan:
Untuk links yang Eastern Town Hall, masih kurang untuk Eastern Town Hall Indonesia Discord

**Comment by andrecahyadi** [comment]
Some minor revisions and additions, closing this issue
