### ISSUE TITLE
Create Google Sheet to monitor reward wallet transactions

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-operations#14]
**Tasks:**

- [x] Create Google Sheet to monitor/track input and output of Cardano Indonesia wallet transactions
https://docs.google.com/spreadsheets/d/14WhaNPi62VKG8p7C2iu8PSkcRZVVNvHegHzz54LmUIE/edit#gid=0
- [x] Please inform @andreassosilo so that he could transfer the tokens + NFT + ADA for event rewards to this wallet
- [x] Stake the ADA to earn rewards 
- [x] Update the Google Sheet accordingly after that

**Comment by andrecahyadi** [comment]
Google sheet dan wallet sudah ready ya bro @andreassosilo

**Comment by andreassosilo** [comment]
Done. Closed
