### ISSUE TITLE
Create Google Sheet & Chart for Cardano Indonesia Social Media Growth

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-operations#16]
**Tasks:**

- [X] Create Google Sheet for monitoring growth of Cardano Indonesia social media
https://docs.google.com/spreadsheets/d/1suCmuWlZm6jgK67lMWZJP77Fqzb4isye-AO_Zgidri8/edit
- [x] Take data on 31 Jan 2022 from number of members in Telegram, Discord, Twitter, Instagram, YouTube
- [x] Create a chart based on it
- [x] Inform other team members

**Comment by andrecahyadi** [comment]
@dionsetyotomo @andreassosilo untuk google sheet sudah tersedia, isinya member yang sudah RSVP dan yang hadir ketika workshop

**Comment by dionsetyotomo** [comment]
ok done
