### ISSUE TITLE
Create Cardano Indonesia IdeaScale account & update the necessary information

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-operations#17]
**Tasks:**

- [x] @andrecahyadi will create IdeaScale account using cardanoindonesiaofficial@gmail.com
username: Cardano Indonesia Official
password: same with email
role: community manager; other/prefer not to say
- [x] @andrecahyadi will add our Cardano Indonesia wallet address in the profile
Added wallet address in the profile, addr1q8gw0fhyu2mycma6uw6j03dg7gxjy7d2q8rgpv4mr4nfxth04zrrwtdpgmfujckslf75d8xa7syca6py4yew2xlw7v7stzdaq4
- [x] @andreassosilo will fill & update the other necessary information

**Comment by andreassosilo** [comment]
Done. Account created by @andrecahyadi , profile updated by @andreassosilo .
