### ISSUE TITLE
Create linktree for Cardano Indonesia

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-operations#18]
**Tasks:**

- [x] Create linktree account for Cardano Indonesia using our official e-mail : https://linktr.ee/CardanoIndonesia
- [x] Update all social media there for Cardano Indonesia
- [x] Put linktree URL on Twitter
- [x] Put linktree URL on Instagram

**Comment by andreassosilo** [comment]
Done. Updated in Twitter and Instagram.
