### ISSUE TITLE
Create GitHub profile for Cardano Indonesia in .github repository

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-operations#2]
**Tasks:**

- [x] Create .github repository; special repo for GitHub organization profile
- [x] Add README.md
- [x] Include necessary basic information there for Cardano Indonesia organization
