### ISSUE TITLE
Monthly report to Cardano Foundation - January 2022

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-operations#20]
**Tasks:**

- [x] Create recap/monthly report about Cardano Indonesia growth and activities in January 2022
- [x] Post in under Cardano Ambassadors Slack
- [x] Inform Cardano Indonesia Team Members

**Comment by andreassosilo** [comment]
Done. Reported to Cardano Foundation and in Cardano Indonesia Discord.
