### ISSUE TITLE
Create repositories for Catalyst 7 Funded Proposals

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-operations#25]
**Tasks:**

- [x] Create repository for Cardano Hub Indonesia - Workshops
- [x] Create repository for DID for Cardano Indonesia Community
- [x] Create repository for Community Web Portal in Bahasa

**Comment by andreassosilo** [comment]
Repositories created, such as below:
- [Cardano Hub Indonesia - Workshops](https://github.com/cardano-indonesia/cardano-indonesia-workshops)
- [DID for Cardano Indonesia Community](https://github.com/cardano-indonesia/did-for-cardano-indonesia-community)
- [Community Web Portal in Bahasa](https://github.com/cardano-indonesia/community-web-portal-in-bahasa)
