### ISSUE TITLE
Request sub-category "Eastern Town Hall" under Cardano Forum Bahasa Indonesia

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-operations#26]
**Tasks:**

- [ ] Discussion with the team, whether to name it "Eastern Town Hall" or "Catalyst"
- [ ] @andreassosilo will request to Cardano Foundation Team to add it
- [ ] Create e-mail/message with required description for it
