### ISSUE TITLE
Editing Twitter Banner for Cardano Indonesia

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-operations#7]
**Tasks:**

- [x] Use the official "CARDANO" logo on the Twitter banner
- [x] Add "INDONESIA" text + Indonesia flag on it
- [x] Upload the new banner in Google Drive (please provide link in the comment)
