### ISSUE TITLE
Updating social media list of Cardano Indonesia Communities

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-operations#8]
**Tasks:**

- [x] Gather new data, collect from each SPO, YouTuber, etc.
- [x] Update list in [Cardano Forum - Bahasa Indonesia](https://forum.cardano.org/t/penting-daftar-link-social-media-komunitas-cardano-indonesia/74743)
- [x] Update list in [Discord Cardano Indonesia](https://discord.gg/KnXFJftmfn)

**Comment by andreassosilo** [comment]
Done. Updated for the list.
