### ISSUE TITLE
Implement TweetDeck for Cardano Indonesia Twitter Account

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-operations#9]
**Tasks:**

- [x] Change Cardano Indonesia Twitter account to team
- [x] Using TweetDeck
- [x] Invite members Twitter, so they can use Cardano Indonesia Twitter via TweetDeck
- [x] Add @andreassosilo @jordyvincent @YanTirta @dionsetyotomo Twitter handle
- [x] Inform Team on how to use TweetDeck

**Comment by andreassosilo** [comment]
Done. Already informed the team how to use TweetDeck during Team Meeting.
